"""add seating_capacity to product_variants

Revision ID: 2959153e34d1
Revises: 5ab854cafbcf
Create Date: 2026-07-30 13:33:12.448564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2959153e34d1'
down_revision: Union[str, Sequence[str], None] = '5ab854cafbcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('seating_capacity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_variants', 'seating_capacity')
    # ### end Alembic commands ###
